changelog:
  categories:
    - title: "Features"
      labels: ["feature", "enhancement"]

    - title: "Bug fixes"
      labels: ["bug", "fix"]

    - title: "Performance"
      labels: ["perf", "performance"]

    - title: "Security"
      labels: ["security"]

    - title: "Breaking changes"
      labels: ["breaking"]

    - title: "Dependencies"
      labels: ["dependencies"]

    - title: "Documentation"
      labels: ["docs"]

    - title: "Chores"
      labels: ["chore", "refactor"]

    - title: "Miscellaneous"
      labels: ["*"]
      exclude:
        labels: ["automated-pr"]
