name: Accessibility Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src2/**/*.{js,jsx}'

jobs:
  a11y-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Detect NodeJS version
        id: nodejs-version
        run: |
          echo "node_version=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nodejs-version.outputs.node_version }}
          cache: 'npm'

      - name: Remove npmrc and package-lock files
        run: rm -f .npmrc package-lock.json
      
      - name: Install dependencies
        run: npm install

      - name: Run a11y eslint checks on modified files
        run: |
          DIFFED_FILES_TO_LINT=$(git diff origin/${{ github.base_ref }}...HEAD --name-only -- '*.js' '*.jsx')
          if [ -n "$DIFFED_FILES_TO_LINT" ]; then
            echo "Running A11y ESLint on modified files..."
            echo "$DIFFED_FILES_TO_LINT"
            echo "$DIFFED_FILES_TO_LINT" | xargs npx eslint --no-eslintrc --ext .js,.jsx --config .eslintrc.a11y.json
          else
            echo "No JS/JSX files were modified"
          fi
