name: "Post-release automation"
description: "Automates post-release tasks → generate notes, open sync PRs, notify Slack"

env:
  GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WORKFLOW_URL }}

permissions:
  contents: write
  pull-requests: write

on:
  release:
    types: [released]

jobs:
  post_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    - name: Generate release notes if missing
      shell: bash
      run: |
        tag=${{ github.event.release.tag_name }}

        # Fetch current release notes
        body=$(gh api repos/${{ github.repository }}/releases/tags/$tag --jq .body)
        body=${body:-}

        # Check if release notes already contain changelog
        if [[ -n "$body" && "$body" != "null" ]] && \
          grep -qiE "What's[[:space:]]+Changed|Full[[:space:]]+Changelog" <<<"$body"; then
          echo "Release notes already contain changelog, skipping generation."
          exit 0
        fi

        # Generating release notes
        gen=$(gh api --method POST \
                repos/${{ github.repository }}/releases/generate-notes \
                -f tag_name="$tag" --jq .body)

        tmp=$(mktemp)

        if [[ -z "$body" || "$body" == "null" ]]; then
          # No previous notes → just write the generated changelog
          printf '%s\n' "$gen" >"$tmp"
        else
          printf '%s\n\n---\n\n%s\n' "$body" "$gen" >"$tmp"
        fi

        gh release edit "$tag" --notes-file "$tmp"

    - name: Create PR (master → stage)
      id: pr_master_stage
      shell: bash
      run: |
        tag=${{ github.event.release.tag_name }}
        url=$(gh pr list --state open --head master --base stage --json url --jq '.[0].url' || true)

        if [[ -z $url ]]; then
          set +e
          output=$(gh pr create --head master --base stage \
                     --title "Sync master to stage after $tag" \
                     --body  "Automated sync PR after $tag." 2>&1)
          status=$?
          set -e
          if [[ $status -eq 0 ]]; then
            url=$(echo "$output" | tail -n1)
          else
            echo "::notice::No commits between master and stage - skipping PR"
            url="N/A"
          fi
        fi

        if [[ $url == https:* ]]; then
          gh pr edit "$url" --add-label automated-pr || true
          num=${url##*/}
        else
          num="N/A"
        fi

        echo "url=$url"   >>"$GITHUB_OUTPUT"
        echo "number=$num" >>"$GITHUB_OUTPUT"

    - name: Create PR (stage → develop)
      id: pr_stage_develop
      shell: bash
      run: |
        tag=${{ github.event.release.tag_name }}
        master_stage_url=${{ steps.pr_master_stage.outputs.url }}
        url=$(gh pr list --state open --head stage --base develop --json url --jq '.[0].url' || true)

        if [[ -z $url ]]; then
          set +e
          output=$(gh pr create --head stage --base develop \
                     --title "Sync stage to develop after $tag" \
                     --body  "Please merge the master → stage PR first:\n${master_stage_url}" 2>&1)
          status=$?
          set -e
          if [[ $status -eq 0 ]]; then
            url=$(echo "$output" | tail -n1)
          else
            echo "::notice::No commits between stage and develop - skipping PR"
            url="N/A"
          fi
        fi

        if [[ $url == https:* ]]; then
          gh pr edit "$url" --add-label automated-pr || true
        fi

        echo "url=$url" >>"$GITHUB_OUTPUT"

    - name: Resolve actor email
      id: actor_email
      shell: bash
      run: |
        email=$(gh api users/${{ github.actor }} --jq .email 2>/dev/null || echo "")
        echo "email=$email" >>"$GITHUB_OUTPUT"

    - name: Send Slack notification
      shell: bash
      run: |
        pr1="${{ steps.pr_master_stage.outputs.url }}"
        pr2="${{ steps.pr_stage_develop.outputs.url }}"

        payload=$(jq -n \
          --arg event "post_release" \
          --arg title "Release ${{ github.event.release.tag_name }} published" \
          --arg body  "Release notes: ${{ github.event.release.html_url }}" \
          --arg actor "${{ steps.actor_email.outputs.email }}" \
          --arg postReleaseStagePR   "$pr1" \
          --arg postReleaseDevelopPR "$pr2" \
          '{event:$event,
            title:$title,
            body:$body,
            actor:$actor,
            postReleaseStagePR:$postReleaseStagePR,
            postReleaseDevelopPR:$postReleaseDevelopPR}')

        curl -s -X POST -H 'Content-Type: application/json' \
             --data "$payload" "$SLACK_WEBHOOK_URL"
